name: hurricane-inference
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.2.*
  - torchvision=0.17.*
  - torchaudio=2.2.*
  - cpuonly
  - gdown>=5.1.0
  - pillow
  - pandas
  - matplotlib
  - seaborn
  - numpy<2
  - scikit-learn
  - tqdm
  - ipywidgets
  - geopandas
  - shapely
  - optuna
  - wandb
  - tensorboard
  - pip
